--7.1
CREATE MATERIALIZED VIEW mat_birthday_czar AS
	SELECT firstName, lastName, TRUNC(MONTHS_BETWEEN(SYSDATE, birthdate)/12) AS age, birthdate
	FROM Person;
	
--7.1.a
SELECT firstName, lastName, birthdate
FROM mat_birthday_czar
WHERE birthdate >= TO_DATE ('01-JAN-1961') AND birthdate <= TO_DATE ('30-DEC-1975');
--The query works since it is not changing any of the tuples in the materialized view.

--7.1.b
UPDATE Person
SET birthdate = '18-JUL-1965'
WHERE firstName = 'Doug' AND birthdate IS NULL;

--This one does not work since materialized view cannot update without FOR UPDATE.

--7.1.c
INSERT INTO birthday_czar VALUES ('Chris','Li',21,'18-JUL-1995');

--First of all, since the view is now materialized, you would need the FOR UPDATE AS in order to even hope to make any edits to the view.

--This line doesn't work and gives the error "virtual column not allowed here." I imagine that since
--age is an attribute that is generated by TRUNC, it is not a legitimate attribute for the table itself.

--If we include the ID into select and insert and remove age, then the insertion works. First of all, we
--removed the virtual column made by TRUNC and we bypassed a constraint by adding a variable for ID which cannot be NULL

--7.1.d
DROP VIEW birthday_czar;

--Deleting the materialized view has no effect on the table itself.