--7.1
CREATE VIEW birthday_czar AS
	SELECT firstName, lastName, TRUNC(MONTHS_BETWEEN(SYSDATE, birthdate)/12) AS age, birthdate
	FROM Person;
	
--7.1.a
SELECT firstName, lastName, birthdate
FROM birthday_czar
WHERE birthdate >= TO_DATE ('01-JAN-1961') AND birthdate <= TO_DATE ('30-DEC-1975');

--7.1.b
UPDATE Person
SET birthdate = '18-JUL-1965'
WHERE firstName = 'Doug' AND birthdate IS NULL;

--Yes, Doug is now included into the query.  Because his birthdate which previously
--was NULL is now inside of the range of Gen X, he is eligible to be selected by the previous query.

--7.1.c
INSERT INTO birthday_czar VALUES ('Chris','Li',21,'18-JUL-1995');

--This line doesn't work and gives the error "virtual column not allowed here." I imagine that since
--age is an attribute that is generated by TRUNC, it is not a legitimate attribute for the table itself.

--If we include the ID into select and insert and remove age, then the insertion works. First of all, we
--removed the virtual column made by TRUNC and we bypassed a constraint by adding a variable for ID which cannot be NULL

--7.1.d
DROP VIEW birthday_czar;

--This doesn't affect the tables in any way as I received the exact same results as I did in 7.1.b while simply replacing
--FROM birthday_czar with Person. The view is a mechanism to perform queries on the tables, therefore the table itself would
--not be affected.