SELECT * FROM DEPARTMENTS;

SELECT COUNT(*) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY>15000;

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE between '01/JAN/02' and '01/JAN/05';

SELECT * FROM EMPLOYEES
WHERE PHONE_NUMBER NOT LIKE '515%';

SELECT FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
AND DEPARTMENTS.DEPARTMENT_NAME = 'Finance'
ORDER BY FIRST_NAME ASC;

SELECT CITY, STATE_PROVINCE, COUNTRIES.COUNTRY_NAME
FROM LOCATIONS, COUNTRIES, REGIONS
WHERE LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
AND COUNTRIES.REGION_ID = REGIONS.REGION_ID
AND REGION_NAME = 'Asia';

SELECT CITY
FROM LOCATIONS
WHERE STATE_PROVINCE IS NULL;